### ISSUE TITLE
[BUG] Status: Failed and "progress":"12 out of 16 workflows completed successfully."

### ISSUE THREAD

**Issue by rnpramasamyai** [Azure-Samples/graphrag-accelerator#100]
When I attempted to check the status of an indexing job from quickstart notebook, I encountered the following error:

{"status_code":200,"index_name":"wiki","storage_name":"styzw4pkgwycpyy","status":"failed","percent_complete":75.0,"progress":"12 out of 16 workflows completed successfully."}

The job automatically reran, and this time I received the following result:
{"status_code":200,"index_name":"wiki","storage_name":"styzw4pkgwycpyy","status":"running","percent_complete":6.25,"progress":"Workflow create_base_extracted_entities started."}

**Issue Description:**
After 2 hours, I checked the status of the indexing job again and observed the following issue:
{"status_code":200,"index_name":"wiki","storage_name":"styzw4pkgwycpyy","status":"running","percent_complete":6.25,"progress":"Workflow create_base_extracted_entities started."}

**If I try to query, I am getting below error:**
{"detail":"14e82e66fdfe12e237b8dc28311ed86e not ready for querying."}

###  Indexing job is continuously running and not completing the job. It keeps running and never stops. If it reaches 100%, it starts from 0% again.

Azure Portal:
![image](https://github.com/user-attachments/assets/f68da684-2228-42cd-a98e-edfba4a8d490)

I checked pods logs:
![image](https://github.com/user-attachments/assets/d79a7a82-3f6c-44ce-a744-8a930d0d7899)

I didn't find any errors on Logs.

Any help?

**Comment by rnpramasamyai** [comment]
Now I am getting this error: "Rate limit is exceeded. Try again in 31 seconds."
![image](https://github.com/user-attachments/assets/d96ae995-e656-4b93-82b0-813951f03a05)

**Comment by timothymeyers** [comment]
@rnpramasamyai - are you still observing the initial behavior where indexing restarts after a failure?

Couple things to note:
* Indexing can definitely take a while, especially if your LLM models are rate limited (which is evidenced by the 429 'Rate Limit Exceeded' errors in your second comment). Indexing will continue retrying until your rate limit abates.
* The 429 errors are expected when you are rate limited and hit your quota; you can try a model deployment in a different region, using a global sku, or requesting a quota increase.

Given the question about indexing failing and then restarting, you may want to consider posting a question in https://github.com/microsoft/graphrag/discussions since I think this may be more about how the indexing process within the GraphRAG Library works and less about how the accelerator deploys the GraphRAG library.

I'll work with the team to look into if there's an issue (possibly in how APIM is configured) in how things are deployed, however.

**Comment by rnpramasamyai** [comment]
@[timothymeyers](https://github.com/timothymeyers)

Below are model deployment details:
GPT-4o
<img width="594" alt="image" src="https://github.com/user-attachments/assets/a046de80-6bc8-4b20-9d2a-fdebaec417be">

Embedding:
<img width="643" alt="image" src="https://github.com/user-attachments/assets/601be690-961d-4259-99de-c611ecda0b99">

**But I still have  an "429 Rate Limit Exceeded" error.**

Any help?

**Comment by rnpramasamyai** [comment]
@Zochory
I have tweaked the configurations in "backend/src/api/pipeline-settings.yaml," but I am still experiencing the same issue.

**Comment by rnpramasamyai** [comment]
I uploaded my own data, tried to index it, and the indexing was done successfully.
<img width="465" alt="image" src="https://github.com/user-attachments/assets/a032c2f7-5897-442b-8386-8409b586e299">

Thank you all.
