### ISSUE TITLE
When deploying the graphrag backend docker image to ACR

### ISSUE THREAD

**Issue by rnpramasamyai** [Azure-Samples/graphrag-accelerator#67]
I was getting below  errors When I ran "bash deploy.sh -p deploy.parameters.json":
Error 1. When deploying the graphrag backend docker image to ACR
<img width="947" alt="image" src="https://github.com/Azure-Samples/graphrag-accelerator/assets/175098560/16b4cbdf-b858-4301-8496-66e756549582">

Error 2. Assigning 'Cognitive Services OpenAI Contributor' AOAI role to managed identity
<img width="656" alt="image" src="https://github.com/Azure-Samples/graphrag-accelerator/assets/175098560/3ac95c2a-b33d-4c05-811b-c2c68dfd27ed">

Pls help me to deploy this repo on azure and pls update deployment documentation.

**Comment by timothymeyers** [comment]
@rnpramasamyai - For Error 1, can you remove `> /dev/null 2>&1` from [this line](https://github.com/Azure-Samples/graphrag-accelerator/blob/497aa5e176c422c958b850e8d65a4d11df3d665e/infra/deploy.sh#L532) in `deploy.sh` and try rerunning to get more context on the error?

**Comment by mobehairy** [comment]
> @rnpramasamyai - For Error 2, can you please confirm that you have the required RBAC permissions in your subscription to do the deployment?
> 
> https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md#rbac-permissions

I am facing the same issue,
my account has contributor and rbac administrator roles
how to troubleshoot?

**Comment by rnpramasamyai** [comment]
Hello @timothymeyers,
I have granted those two permissions to my Azure account and am trying to deploy a bash script using that account.

**Comment by vansen** [comment]
I am running into the same issue for Error 2. i can confirm the following permissions are granted on subscription level: 
![image](https://github.com/Azure-Samples/graphrag-accelerator/assets/13270526/c935da4c-d346-45f8-9a3a-4eec87e2db5b)
Is there any solution/hint on how to troubleshoot please? Thank you

**Comment by rnpramasamyai** [comment]
To whom should I assign the above permissions? Currently logged-in user or managed identity?

**Comment by vansen** [comment]
that seems to be a different error, I get a more generic one: 
![image](https://github.com/Azure-Samples/graphrag-accelerator/assets/13270526/2ae6f44e-be79-49fa-80e0-deff1ee5af48)

**Comment by mobehairy** [comment]
Yes, after making sure of permissions granted to my account
i found that we should put $GRAPHRAG_API_BASE for Azure OpenAI (AOAI) to be the endpoint 
Open your Azure OpenAI (AOAI) resource on Azure and get endpoint
https://<AOAI Name>.openai.azure.com/

**Comment by vansen** [comment]
Thanks - but I have already set this to the correct value. So unfortunately not the solution in my case.

**Comment by mobehairy** [comment]
ok, you need to make sure of $servicePrincipalId and $scope 

to make sure that it the correct IDs, Put in section >> assignAOAIRoleToManagedIdentity()
echo $servicePrincipalId
echo $scope 
and make sure that it get the correct IDs

**Comment by GabrieleCastellani** [comment]
I had the same issue.
I had installed the new AOAI service from the new AI Hub portal. 
Installing the old one (with the OpenAI Logo) did the trick.
![image](https://github.com/Azure-Samples/graphrag-accelerator/assets/8189074/b373adbe-9523-4c78-b1ce-cf70377f3c7f)

Also be sure that you have specified the right GRAPHRAG_API_BASE

"GRAPHRAG_API_BASE": "https://xxx.openai.azure.com/",

This made the trick

**Comment by rnpramasamyai** [comment]
I tried to redeploy this repo on azure using bash deploy.sh -p deploy.parameters.json, I faced the following errors:

1. Couldn't build docker image and push it to ACR.
2. Assigning 'Cognitive Services OpenAI Contributor' AOAI role to managed identity.
3. Assigning 'ACRPull' role to AKS to access container registry.
4. Peering apim vnet to aks.

**Comment by vansen** [comment]
Yes, that pointed me into the right direction. I was switching the subscription earlier, but the OpenAI Service was still in the old subscription, therefore the access to that was of course not possible. Now I got it working. Thanks

**Comment by timothymeyers** [comment]
@rnpramasamyai

For 1, see #45 for some tips. This looks like a challenge with the Azure CLI that has popped up over the years. Also see https://github.com/Azure/azure-cli/issues/22301

For 2, this error comes from [this method in deploy.sh](https://github.com/Azure-Samples/graphrag-accelerator/blob/61aff40603f2f491c6b21102df814106da7a9974/infra/deploy.sh#L265). Line 267 is what is failing but that is because the `scope` local variable is not being set correctly on 265. Is your `GRAPHRAG_API_BASE` variable set correctly in `deploy.parameters.json`? It should look like `"GRAPHRAG_API_BASE": "https://<aoai-name>.openai.azure.com/"`

For 3, I might need more context on what you're seeing, but it likely is a result of [this line](https://github.com/Azure-Samples/graphrag-accelerator/blob/61aff40603f2f491c6b21102df814106da7a9974/infra/deploy.sh#L279) failing. You can remove `> /dev/null 2>&1` from the line to get more error output.

For 4, I need to see more output.

For 5, I'm not sure how you got to this point given the above issues, but if you actually have a pod running, you can check the logs for the graphrag-index and graphrag-query pods in AKS (via the Portal or using `'kubectl`) to see what errors they are running into.

**Comment by rnpramasamyai** [comment]
I am using following versions:
azure-cli                         2.61.0 *

core                              2.61.0 *
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

**Comment by rnpramasamyai** [comment]
@timothymeyers 
I solved all above errors.

Now I got  new error:
<img width="569" alt="image" src="https://github.com/user-attachments/assets/7960c2a0-4d23-403e-bd7f-c9ba09ad8a71">

Any help to fix helm issue?
