### ISSUE TITLE
[BUG] existing container registry leads to deploy.sh failed

### ISSUE THREAD

**Issue by Elizabeth819** [Azure-Samples/graphrag-accelerator#87]
**Describe the bug**
The first time deploy.sh failed, with a python glib missing, after installation, the second time deploy.sh failed because the first time a container registry was created. Shall I delete the storage account?

**To Reproduce**

**Expected behavior**
Automatically continue deployment with existing container regiestry

**Screenshots**
![image](https://github.com/user-attachments/assets/9d037f67-f3cc-4d00-ac29-1c0909bc79ec)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jasonclane** [comment]
There is a pull request awaiting approval that might fix your problem: https://github.com/Azure-Samples/graphrag-accelerator/pull/88

**Comment by jgbradley1** [comment]
@Elizabeth819 the PR that @jasonclane is referring to has been merged. Can you try again and let me know if your problem still exist? I wasn't tracking that a python glib was necessary but azure cli is a python package underneath, so that could explain the problem. We have the software requirements for deployment listed [here](https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md#prerequisites) or you can open the repo in a devcontainer which will automatically include all the required tools and appropriate version requirements.

**Comment by timothymeyers** [comment]
Closing this as stale. Possibly fixed by #88 or #106 if there was an issue.
